# Generated by Django 5.1.6 on 2025-08-08 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentscore',
            name='student_sco_total_s_b3e2a1_idx',
        ),
        migrations.AddField(
            model_name='studentscore',
            name='class_average',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Class average score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='studentscore',
            index=models.Index(fields=['created_at'], name='student_sco_created_f26c5e_idx'),
        ),
    ]
