# Generated by Django 5.1.6 on 2025-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentscore_student_sco_total_s_b3e2a1_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentscore',
            index=models.Index(fields=['total_score'], name='student_sco_total_s_b3e2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentscore',
            index=models.Index(fields=['student', 'total_score'], name='student_sco_student_159354_idx'),
        ),
        migrations.AddIndex(
            model_name='studentscore',
            index=models.Index(fields=['subject', 'total_score'], name='student_sco_subject_43605c_idx'),
        ),
    ]
