# Generated by Django 5.1.6 on 2025-08-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_teacherperformance_teacher_studentattendance_teacher_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_first_n_ce3d36_idx'),
        ),
    ]
